colunas: ['author', 'title', 'abstract', 'year', 'type_publication', 'doi', 'issn']
formato_salvar_arquivo: csv

#*******************************************************************
# exemplo de filtro. Excluir os campos que não fazem parte do filtro
#*******************************************************************
# filtros: '{
#   "sourceid": [28773,20315], "sourceid": [5800175970]
#   "title": ["title1","title2"], 
#   "abstract": [""],
#   "year": [], 
#   "type_publication: [""], 
#   "doi": [], 
# }' 

filtros: '{ 
  "year": [2014,2016],
  "title": ["LEADERSHIP","BIG DATA"]
}'

api:
  filtro: data+quality+AND+big+data
  ieee: 
    url: http://ieeexploreapi.ieee.org/api/v1/search/articles?format=json&apikey=2ry5drreqneft9t8tdn5xyuz&max_records=200
  total_consultas: 5


